/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchIndividualPanel.java
 *
 * Created on Jan 2, 2011, 10:18:20 PM
 */
package net.sourceforge.gedprint.gui.action;

import net.sourceforge.gedprint.gedcom.Record;

/**
 *
 * @author nigjo
 */
public class SearchIndividualPanel extends javax.swing.JPanel
{
  /** Creates new form SearchIndividualPanel */
  public SearchIndividualPanel()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JLabel lbl_query = new javax.swing.JLabel();
    querytext = new javax.swing.JTextField();
    javax.swing.JButton btnSearch = new javax.swing.JButton();
    javax.swing.JLabel lbl_results = new javax.swing.JLabel();
    javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    results = new javax.swing.JList();

    lbl_query.setText(Utilities.getString("SearchIndividualPanel.lbl_query.text")); // NOI18N

    querytext.setColumns(20);

    btnSearch.setText(Utilities.getString("SearchIndividualPanel.btnSearch.text")); // NOI18N
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    lbl_results.setText(Utilities.getString("SearchIndividualPanel.lbl_results.text")); // NOI18N

    jScrollPane1.setViewportView(results);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lbl_query)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(querytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSearch))
          .addComponent(lbl_results))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_query)
          .addComponent(querytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSearch))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lbl_results)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
  {//GEN-HEADEREND:event_btnSearchActionPerformed
    String query = querytext.getText().trim();
    // TODO search
  }//GEN-LAST:event_btnSearchActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JTextField querytext;
  javax.swing.JList results;
  // End of variables declaration//GEN-END:variables

  Record getSelectedRecord()
  {
    Object selectedValue = results.getSelectedValue();
    //TODO throw new UnsupportedOperationException("Not yet implemented");
    return null;
  }
}
